export type DeclaraIR = 'NAO DECLARA IR' | 'DECLARA IR'
export type TipoIR = 'SIMPLES' | 'COMPLETO' | 'NAO SABE'
export type CondicaoTrabalho = 'CLT' | 'SERVIDOR PUBLICO' | 'OUTRO'
export type PlanoPrevidencia = 'VGBL' | 'PGBL'
export type RegimeTributarioIR = 'PROGRESSIVO' | 'REGRESSIVO'
export type Table = 'DadosSimulacao' | 'Fundo' | 'Rentabilidade' | 'Resultado' | 'Simulacao'